### ISSUE TITLE
Issue connecting

### ISSUE THREAD

**Issue by camifran** [trap000d/dropbox-kindle-client#1]
Hi, i followed your installation instructions and edited the dropbox.cfg file like this:

```
[server]
library = KindleTK
token = (mytoken) 

[kindle]
local = /mnt/us/documents/Dropbox
upload = /KmeKV
```

I created all the folders manually, both in Dropbox and in my kindle.

When I try to sync, a connection error pops up, path not found or something like that flashes on the bottom of the screen.

The log:

```
eips: pixel_in_range> (1088, 1416) pixel not in range (0..1072, 0..1448)
eips: pixel_in_range> (1088, 1416) pixel not in range (0..1072, 0..1448)
409 Client Error: Conflict for url: https://api.dropboxapi.com/2/files/get_metadata
```

Any help? thank you!

**Comment by trap000d** [comment]
I tried to reproduce the issue from all 3 my Kindles and 4 different WiFi access points.

409 Conflict
    Indicates that the request could not be processed because of conflict in the request, such as an edit conflict between multiple simultaneous updates.

Dropbox API reference explains it as:

Endpoint-specific error. Look to the JSON response body for the specifics of the error.

For python requests package they said it could be a conflict with proxy so why I suggested that you check your proxy settings.

Another reason for error 409 is an empty folder (see discussion here: https://github.com/dropbox/dropbox-sdk-python/issues/26 ). To be honest, I can't remember if I ever tested the client in such condition. I'll check it and let you know. 

UPD. It's not an empty folder

**Comment by camifran** [comment]
Hi, thanks for replying!

I don't have a proxy set up in my computer. 

Is there any other thing I can try or log I can send you?

Thanks!

PS: I put the library folder at my Dropbox root. Is that ok?

**Comment by trap000d** [comment]
Hi Camifran,
After some more tests It looks like you've created Dropbox app with restricted permissions ("App Folder", not "Full Dropbox"). In this case your folder is created in Dropbox as /Apps/KindleTK and "get_metadata" API function doesn't work for it (and some other I suspect).
You should either create app and generate token for "Full Dropbox" access or give me some time to sort it out.

P.S. For me App folder access is useful only for some specific applications (like Mozilla Thunderbird link attachment) but not for everyday usage as these apps have so much restrictions.

Regards,

**Comment by camifran** [comment]
Hi trap,

Thank you! This solved my problem. Working flawlessly! I truly believe this is a game changer, being able to download a book, save it to dropbox from say, a cellphone, and then pulling it directly from your kindle. You rock!
